# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:

  # Cluster configs for each environment
  default-cluster-spec: &default-cluster-spec
    spark_version: '12.0.x-cpu-ml-scala2.12'
    node_type_id: 'i3.xlarge' # NOTE: this is an AWS-specific instance type. Change accordingly if running on Azure or GCP.
    driver_node_type_id: 'i3.xlarge'  # NOTE: this is an AWS-specific instance type. Change accordingly if running on Azure or GCP.
    num_workers: 1
    # To reduce start up time for each job, it is advisable to use a cluster pool. To do so involves supplying the following
    # two fields with a pool_id to acquire both the driver and instances from.
    # If driver_instance_pool_id and instance_pool_id are set, both node_type_id and driver_node_type_id CANNOT be supplied.
    # As such, if providing a pool_id for driver and worker instances, please ensure that node_type_id and driver_node_type_id are not present
    #    driver_instance_pool_id: '0617-151415-bells2-pool-hh7h6tjm'
    #    instance_pool_id: '0617-151415-bells2-pool-hh7h6tjm'

  dev-cluster-config: &dev-cluster-config
    new_cluster:
      <<: *default-cluster-spec

  staging-cluster-config: &staging-cluster-config
    new_cluster:
      <<: *default-cluster-spec

  prod-cluster-config: &prod-cluster-config
    new_cluster:
      <<: *default-cluster-spec

environments:
  dev:
    workflows:
      - name: "DEV-churn-classification-dbx-feature-table-refresh"
        tasks:
          - task_key: "main"
            <<: *dev-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "feature_table_refresh"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/dev/.dev.env',
                            '--conf-file', 'file:fuse://conf/tasks/feature_table_refresh_config.yml' ]
      - name: "DEV-churn-classification-dbx-model-train"
        tasks:
          - task_key: "main"
            <<: *dev-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_train"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/dev/.dev.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_train_config.yml' ]
      - name: "DEV-churn-classification-dbx-model-sanity-check"
        tasks:
          - task_key: "main"
            <<: *dev-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_sanity_check"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/dev/.dev.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_sanity_check_config.yml' ]
      - name: "DEV-churn-classification-dbx-model-deployment"
        tasks:
          - task_key: "main"
            <<: *dev-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_deployment"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/dev/.dev.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_deployment_config.yml' ]
      - name: "DEV-churn-classification-dbx-model-inference-batch"
        tasks:
          - task_key: "main"
            <<: *dev-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_inference_batch"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/dev/.dev.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_inference_batch_config.yml' ]
  staging:
    workflows:
      - name: "STAGING-churn-classification-dbx-feature-table-refresh"
        tasks:
          - task_key: "main"
            <<: *staging-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "feature_table_refresh"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/staging/.staging.env',
                            '--conf-file', 'file:fuse://conf/tasks/feature_table_refresh_config.yml' ]
      - name: "STAGING-churn-classification-dbx-model-train"
        tasks:
          - task_key: "main"
            <<: *staging-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_train"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/staging/.staging.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_train_config.yml' ]
      - name: "STAGING-churn-classification-dbx-model-sanity-check"
        tasks:
          - task_key: "main"
            <<: *staging-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_sanity_check"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/staging/.staging.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_sanity_check_config.yml' ]
      - name: "STAGING-churn-classification-dbx-model-deployment"
        tasks:
          - task_key: "main"
            <<: *staging-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_deployment"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/staging/.staging.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_deployment_config.yml' ]
      - name: "STAGING-churn-classification-dbx-model-inference-batch"
        tasks:
          - task_key: "main"
            <<: *staging-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_inference_batch"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/staging/.staging.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_inference_batch_config.yml' ]
      - name: "STAGING-churn-classification-dbx-integration-test"
        tasks:
          - task_key: "main"
            <<: *staging-cluster-config
            spark_python_task:
              python_file: "file://tests/integration/integration_test.py"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/staging/.staging.env',
                            '--feature_table_refresh_config', 'file:fuse://conf/tasks/feature_table_refresh_config.yml',
                            '--model_train_config', 'file:fuse://conf/tasks/model_train_config.yml',
                            '--model_deployment_config', 'file:fuse://conf/tasks/model_deployment_config.yml',
                            '--model_inference_batch_config', 'file:fuse://conf/tasks/model_inference_batch_config.yml' ]
  prod:
    workflows:
      - name: "PROD-churn-classification-dbx-feature-table-refresh"
        tasks:
          - task_key: "main"
            <<: *prod-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "feature_table_refresh"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/prod/.prod.env',
                            '--conf-file', 'file:fuse://conf/tasks/feature_table_refresh_config.yml' ]
      - name: "PROD-churn-classification-dbx-model-train"
        tasks:
          - task_key: "main"
            <<: *prod-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_train"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/prod/.prod.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_train_config.yml' ]
      - name: "PROD-churn-classification-dbx-model-sanity-check"
        tasks:
          - task_key: "main"
            <<: *prod-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_sanity_check"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/prod/.prod.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_sanity_check_config.yml' ]
      - name: "PROD-churn-classification-dbx-model-deployment"
        tasks:
          - task_key: "main"
            <<: *prod-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_deployment"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/prod/.prod.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_deployment_config.yml' ]
      - name: "PROD-churn-classification-dbx-model-inference-batch"
        tasks:
          - task_key: "main"
            <<: *prod-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "model_inference_batch"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/prod/.prod.env',
                            '--conf-file', 'file:fuse://conf/tasks/model_inference_batch_config.yml' ]
      - name: 'PROD-churn-classification-dbx-initial-model-train-register'
        tasks:
          - task_key: 'feature-table-refresh'
            <<: *prod-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "feature_table_refresh"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/prod/.prod.env',
                            '--conf-file', 'file:fuse://conf/tasks/feature_table_refresh_config.yml' ]
          - task_key: 'model-train'
            <<: *prod-cluster-config
            python_wheel_task:
              package_name: "churn_classification_dbx"
              entry_point: "feature_table_refresh"
              parameters: [ '--base-data-params', 'file:fuse://conf/.base_data_params.env',
                            '--env', 'file:fuse://conf/prod/.prod.env',
                            '--conf-file', 'file:fuse://conf/tasks/feature_table_refresh_config.yml' ]

