name: CI pipeline

on:
  pull_request:
    branches:
      - main
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    environment: "STAGING"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_STAGING_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_STAGING_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -e ".[local,test]"

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests/unit

      - name: Deploy integration test [staging environment] (assets only upload)
        run: |
          dbx deploy STAGING-churn-classification-dbx-integration-test --environment=staging --assets-only

      - name: Run integration test in a jobless fashion [staging environment]
        run: |
          dbx launch STAGING-churn-classification-dbx-integration-test --environment=staging --from-assets --trace

